theme: jekyll-theme-cayman

# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
safe: true
markdown_ext: md

##############################################################################

# Site settings

name: ud_doc
homeurl: ""
editurl: "https://github.com/msimi/ud_doc/edit/master"
issueurl: "https://github.com/msimi/ud_doc/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
output: true
